Lint/HandleExceptions:
  Exclude:
    - 'lib/spore/rails.rb'
    - 'lib/spore.rb'

Style/Documentation:
  Exclude:
    - 'Rakefile'
    - 'lib/spore/version.rb'

Style/FileName:
  Exclude:
    - 'lib/spore/rails-now.rb'
    - 'lib/spore-rails.rb'

Style/HashSyntax:
  EnforcedStyle: 'hash_rockets'

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'
